USE IT_EXPECT;
CREATE TABLE users(
   id INT AUTO_INCREMENT,
   firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    email VARCHAR(70) NOT NULL,
    password VARCHAR(255) NOT NULL,
   PRIMARY KEY(id)
);